service: aws-python-http-api-project-cm
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  bye:
    handler: handler.byebye
    events:
      - httpApi:
          path: /bye
          method: get

